### ISSUE TITLE
Car stuck in wall

### ISSUE THREAD

**Issue by Jeb4dev** [JesperKauppinen/DefectiveDickDriver#5]
Car may get stuck in wall: 
https://cdn.discordapp.com/attachments/826558025488793673/826765061951324170/unknown.png

**Comment by ghost** [comment]
I think this has something to do with the scale of the wall, the collisions don't seem to correctly detect as you can generally clip pretty far into a wall.

**Comment by ghost** [comment]
Might try to shrink them down in size, see if we can't get better results.
